apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql-server
spec:
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-server
        tier: backend
        track: stable
    spec:
      containers:
      - image: mysql:5.7
        resources:
          limits:
            cpu: 0.5      
        name: mysql-server
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: ${MYSQL_PASSWORD}
        ports:
          - name: mysqld
            containerPort: ${DB_INTERNAL_PORT}       
        volumeMounts:
        - name: mysql-disk
          mountPath: /var/lib/mysql
      volumes:
        - name: mysql-disk
          persistentVolumeClaim:
            claimName: mysql-pv-claim